### ISSUE TITLE
Certificate for private sector?

### ISSUE THREAD

**Issue by David-Jimenez-Bermejo** [psmiraglia/spid-compliant-certificates#3]
Is it possible create a certificate for provate sector?
I'm trying without docker. I changed "spid_sector" to private in spid_public.conf but I always obtain the following error:

```
problem creating object organizationIdentifier=2.5.4.97
error:08064066:object identifier routines:OBJ_create:oid exists:crypto\objects\obj_dat.c:698:
```

**Comment by psmiraglia** [comment]
Management of private sector certificates is still a work in progress feature. Anyway, according to Avviso SPID n.29, certificates for private sector can not be self-signed.

About the error you're referring to, it is related to double definition of `organizationIdentifier`. In recent OpenSSL versions, it's already defined. The error can be fixed by commenting the definition within `*.conf` files.
